### ISSUE TITLE
Vue-ua vs vue-gtm?

### ISSUE THREAD

**Issue by awitherow** [ScreamZ/vue-analytics#16]
What does https://github.com/mib200/vue-gtm not have that vue-ua does have?

Do you know about the existence of this library?

Have you considered adopting the feature set into your own?

**Comment by ScreamZ** [comment]
Hey,

Didn't known about that lib, it seems to be a FORK of mine. :-)

Google tag manager is really nice, I love it, but we must think in order to avoid tight coupling with it. Many people are using Google Analytics without the needs of loading a full stack of GTM.

I keep in mind a way to support "dataLayer" feeding through this lib but is it really a priority ?
In fact the main goal of GTM is to avoid coding in app and separate the release process from tags management, dataLayer is used in particular case where this is hard to deal with common GTM server based rules...

Hope I answered your question ?

Best regards

**Comment by awitherow** [comment]
Makes complete sense. I guess having multiple libraries is the only way to do it... 👍
